---
# --- Variables --- #

local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

# --- Release Manager Config --- #

# Required: deployment targets
targets:
  - type              : "awss3"
    access_key_id     : <%= ENV['AWS_ACCESS_KEY'] %>
    secret_access_key : <%= ENV['AWS_SECRET_KEY'] %>

# Required: packages to be deployed
packages:
  # AWS S3 plain upload example
  - name     : "event-manifest-cleaner" # Just for convenience
    bucket   : "snowplow-hosted-assets"
    path     : "4-storage/event-manifest-cleaner"
    region   : "eu-west-1"
    publish  : true
    override : false
    continue_on_conflict : false
    version  : <%= FUNC['sbt_version(.)'] %>

    # Required IF '--check-version' is passed: will assert that both versions are the same
    build_version : <%= ENV['TRAVIS_BUILD_RELEASE_TAG'] %>

    # Optional: Build commands
    build_commands:
      - sbt assembly

    # Required: Artifact. Version will be inserted between prefix and suffix
    artifacts:
      - type   : "asis"
        prefix : "event-manifest-cleaner-"
        suffix : ".jar"
        binary_paths:
          - "target/scala-2.11/event-manifest-cleaner-{{ packages.0.build_version }}.jar"
